[package]
name = "edb-core"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

[dependencies]
edb-compiler = { path = "../compiler" }
edb-emul = { path = "../emul"}
web3 = { path = "../../../rust-web3" }
failure = "0.1.2"
log = "*"
futures = "0.1.23"
