[package]
name = "emul2"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]

[dependencies]
rustc-hex = "1.0"
ethereum-types = "0.3"
log = "0.3"
crossbeam = "0.3"
tempdir = "0.3"
delegate = "0.1.3"
tokio = "0.1.7"
rayon = "1.0.2"
sputnikvm = "0.10.1"
failure = "*"
